const PUSH = '@@ROUTER/PUSH';
const REPLACE = '@@ROUTER/REPLACE';
const GO = '@@ROUTER/GO';
const GO_BACK = '@@ROUTER/GO_BACK';
const GO_FORWARD = '@@ROUTER/GO_FORWARD';
const LOCATION_CHANGED = '@@ROUTER/LOCATION_CHANGED';

export {
  PUSH,
  REPLACE,
  GO,
  GO_BACK,
  GO_FORWARD,
  LOCATION_CHANGED,
};
