const PUSH = '@@ROUTER/PUSH';
const REPLACE = '@@ROUTER/REPLACE';
const GO = '@@ROUTER/GO';
const GO_BACK = '@@ROUTER/GO_BACK';
const GO_FORWARD = '@@ROUTER/GO_FORWARD';
const MANUAL_CHANGE = '@@ROUTER/MANUAL_CHANGE';

export {
  PUSH,
  REPLACE,
  GO,
  GO_BACK,
  GO_FORWARD,
  MANUAL_CHANGE,
};
